trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: false  # 不保留凭据


- task: NodeTool@0
  inputs:
    versionSpec: '12.x'  # 或你所需的Node.js版本
    checkLatest: true
  displayName: 'Setup Node.js'



- script: |
    npm install
  displayName: 'Npm Install'
