trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: test_variable_group  # 引用变量组

steps:
- checkout: self
  persistCredentials: false  # 不保留凭据

- script: |
    echo "Checking _temp directory at the start of the pipeline..."
    ls -l /home/vsts/work/_temp
    for file in /home/vsts/work/_temp/*; do
        echo "Content of $file:"
        cat "$file"
        echo ""
    done
  displayName: 'Check and display _temp directory contents at start'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'test_connection'
    appType: 'functionApp'
    appName: 'mypocfunctiontest'
    package: '$(Build.ArtifactStagingDirectory)/'
  displayName: 'Deploy Azure Function App'

- script: |
    echo "Checking _temp directory after AzureFunctionApp task..."
    ls -l /home/vsts/work/_temp
    for file in /home/vsts/work/_temp/*; do
        echo "Content of $file:"
        cat "$file"
        echo ""
    done
  displayName: 'Check and display _temp directory contents after AzureFunctionApp task'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'  # 或你所需的Node.js版本
    checkLatest: true
  displayName: 'Setup Node.js'

- script: |
    echo "Checking _temp directory after NodeTool task..."
    ls -l /home/vsts/work/_temp
    for file in /home/vsts/work/_temp/*; do
        echo "Content of $file:"
        cat "$file"
        echo ""
    done
  displayName: 'Install Node.js dependencies and display variables'
