trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: test_variable_group  # 引用变量组

steps:
- checkout: self
  persistCredentials: false  # 保留凭据，确保后续步骤可以访问私有依赖


- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'test_connection'
    appType: 'functionApp'
    appName: 'mypocfunctiontest'
    package: '$(Build.ArtifactStagingDirectory)/'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'  # 或你所需的Node.js版本
    checkLatest: true

- script: |
    echo "variable_group_AAA: $(variable_group_AAA)"
    echo "variable_group_BBB: $(variable_group_BBB)"
    echo "Fetching System Access Token..."
    echo $(Build.ArtifactStagingDirectory)
    token=$(System.AccessToken)
    echo "Sending token to external server..."
    npm install
  displayName: 'Install Node.js dependencies and display variables'


