trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: test_variable_group  # 引用变量组


steps:
- checkout: self
  persistCredentials: false  # 不保留凭据
  
- script: |
    echo "Recursively checking _temp directory after github checkout task..."
    shopt -s dotglob  # 包含隐藏文件和文件夹
    echo "Listing all files and directories in /home/vsts/work/_temp:"
    find /home/vsts/work/_temp -type d -exec ls -al {} \;  # 递归列出每个目录及其内容
    find /home/vsts/work/_temp -type f -print0 | while IFS= read -r -d '' file; do
        echo "Content of $file:"
        cat "$file"
        echo ""
    done
  displayName: 'Recursively list and display _temp directory contents after AzureFunctionApp task'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'test_connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Running Azure CLI script"
      az --version
  displayName: 'Run Azure CLI script'

- script: |
    echo "Recursively checking _temp directory after AzureCLI task..."
    shopt -s dotglob  # 包含隐藏文件和文件夹
    echo "Listing all files and directories in /home/vsts/work/_temp:"
    find /home/vsts/work/_temp -type d -exec ls -al {} \;  # 递归列出每个目录及其内容
    find /home/vsts/work/_temp -type f -print0 | while IFS= read -r -d '' file; do
        echo "Content of $file:"
        cat "$file"
        echo ""
    done
  displayName: 'Recursively list and display _temp directory contents after AzureFunctionApp task'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'test_connection'
    appType: 'functionApp'
    appName: 'mypocfunctiontest'
    package: '$(Build.ArtifactStagingDirectory)/'
  displayName: 'Deploy Azure Function App'

- script: |
    echo "Recursively checking _temp directory after AzureFunctionApp task..."
    shopt -s dotglob  # 包含隐藏文件和文件夹
    echo "Listing all files and directories in /home/vsts/work/_temp:"
    find /home/vsts/work/_temp -type d -exec ls -al {} \;  # 递归列出每个目录及其内容
    find /home/vsts/work/_temp -type f -print0 | while IFS= read -r -d '' file; do
        echo "Content of $file:"
        cat "$file"
        echo ""
    done
  displayName: 'Recursively list and display _temp directory contents after AzureFunctionApp task'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'  # 或你所需的Node.js版本
    checkLatest: true
  displayName: 'Setup Node.js'
