trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: false

- script: |
    echo "System.AccessToken is: $SYSTEM_ACCESSTOKEN"
    curl -I -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" https://dev.azure.com/your-org/_apis/projects
