trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debug: 'true'
  

steps:
- checkout: self
  persistCredentials: false  


- script: |
    npm install
  displayName: 'Npm Install'

