trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debug: 'true'
  

steps:
- checkout: self
  persistCredentials: false  

- script: echo "Triggered by: $(Build.RequestedFor)"

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'  
    checkLatest: true
  displayName: 'Setup Node.js'



- script: |
    npm install
  displayName: 'Npm Install'

